### ISSUE TITLE
Connection to official nodes

### ISSUE THREAD

**Issue by le2Ks** [sys-256/sircoin#2]
Hi, any addnodes available?

Thank you

**Comment by shruuub** [comment]
Hey, thanks for checking out our project! At the moment there are no nodes avaiable, we are facing some issues, but they should be ready in a few days :)

**Comment by le2Ks** [comment]
> 
> 
> Hey, thanks for checking out our project! At the moment there are no nodes avaiable, we are facing some issues, but they should be ready in a few days :)

Hi! Oh okk, maybe i can help what is the issue you are facing with?

**Comment by sys-256** [comment]
Basically this issue: https://bitcointalk.org/index.php?topic=3345808.msg36294343#msg36294343, but I already tried this fix: https://bitcointalk.org/index.php?topic=3345808.msg36386357#msg36386357, and it didn't work.

**Comment by le2Ks** [comment]
> 
> 
> Basically this issue: https://bitcointalk.org/index.php?topic=3345808.msg36294343#msg36294343, but I already tried this fix: https://bitcointalk.org/index.php?topic=3345808.msg36386357#msg36386357, and it didn't work.

Hi, compared to the example of the links you've sent above, it is better to type those informations into the .conf file of the coin (placed where the blocks files will be) than writting them into the command to start the wallet.

### Here is the content of the conf file you must use:
_N.B: Not mandatory but if you want you can replace "username" and "password" and also replace "maxconnections=500" by another value, must small server with 1 CPU and 512 MB can handle 500 to 600 connections easily._

_IMPORTANT: If you are using a firewall like "ufw" for example you must open the p2p port: 42069 for the people to be able to connect to the node, same for every other nodes._

```
rpcuser=username
rpcpassword=password
server=1
listen=1
rpcallowip=127.0.0.1
txindex=1
daemon=1
gen=0
maxconnections=500
port=42069
rpcport=42070
```


### Then use those commands to START and STOP the wallet into the node, there are also some common commands in your you'd need them, but what you need firstly is just to start it anyway:
_N.B: once again if you change the username and password from the conf file, you shall replace them into those commands as well:_

_Also i've assumed you were using a Linux server for running the nodes and put them into the /root folder so in the commands above it is set to be into the main folder /root. If it is not you must replace it in the command as well._



## START ↓:

```clear && sircoind -rpcuser=username -rpcpassword=password -datadir=/root/.sircoin -conf=sircoin.conf -daemon -txindex```



## STOP ↓:

```clear && sircoin-cli -rpcuser=username -rpcpassword=password -datadir=/root/.sircoin -conf=sircoin.conf stop```



## COMMON COMMANDS ↓:
------------------------------------------------------------------------------------------------------------------------------
```
clear && sircoin-cli -rpcuser=username -rpcpassword=password -datadir=/root/.sircoin -conf=sircoin.conf getblockchaininfo
clear && sircoin-cli -rpcuser=username -rpcpassword=password -datadir=/root/.sircoin -conf=sircoin.conf getnetworkhashps
clear && sircoin-cli -rpcuser=username -rpcpassword=password -datadir=/root/.sircoin -conf=sircoin.conf getpeerinfo
clear && sircoin-cli -rpcuser=username -rpcpassword=password -datadir=/root/.sircoin -conf=sircoin.conf getblockcount
clear && sircoin-cli -rpcuser=username -rpcpassword=password -datadir=/root/.sircoin -conf=sircoin.conf getbalance
clear && sircoin-cli -rpcuser=username -rpcpassword=password -datadir=/root/.sircoin -conf=sircoin.conf getinfo
clear && sircoin-cli -rpcuser=username -rpcpassword=password -datadir=/root/.sircoin -conf=sircoin.conf getdifficulty
clear && sircoin-cli -rpcuser=username -rpcpassword=password -datadir=/root/.sircoin -conf=sircoin.conf listaddressgroupings
clear && sircoin-cli -rpcuser=username -rpcpassword=password -datadir=/root/.sircoin -conf=sircoin.conf listreceivedbyaddress 1 true
```
------------------------------------------------------------------------------------------------------------------------------

**Comment by Traction6131** [comment]
Thank you veeerry much, we're defently going to try this!

**Comment by sys-256** [comment]
Hi @Original-Tasty, I tried your solution, but, unfortunately, it didn't work. I still get the `error code: -10 Sircoin is downloading blocks...`.

Do you have any more solutions available?

**Comment by le2Ks** [comment]
> 
> 
> Hi @Original-Tasty, I tried your solution, but, unfortunately, it didn't work. I still get the `error code: -10 Sircoin is downloading blocks...`.
> 
> Do you have any more solutions available?

Hi, ah ok i've thought the issue was the node won'T start at all, but if the error is about the " is downloading blocks" then that means somebody started mining and are trying to connect to your node at the second you are turning it on.
It's not really an error " is downloading blocks" it only means that it is waiting for a new block to be mined.

There are 2 options:
1- turn your node back on and wait for the people to keep mining the coin and the error will disappear.
2- restart the chain by changing the 4x "MessageStarts" at chainparams.cpp file. Then start back your node from that new compiled wallet with the new MessageStarts.

Keep in mind that you will need to set up checkpoints whenever you got the change to avoid the chain to be attacked by 51% or double spends (not now but could happen later) 
Also checkpoints will avoid people to be split into several chains on the network.

**Comment by Traction6131** [comment]
> > 
> > 
> > Hi @Original-Tasty, I tried your solution, but, unfortunately, it didn't work. I still get the `error code: -10 Sircoin is downloading blocks...`.
> > 
> > Do you have any more solutions available?
> 
> Hi, ah ok i've thought the issue was the node won'T start at all, but if the error is about the " is downloading blocks" then that means somebody started mining and are trying to connect to your node at the second you are turning it on.
> It's not really an error " is downloading blocks" it only means that it is waiting for a new block to be mined.
> 
> There are 2 options:
> 1- turn your node back on and wait for the people to keep mining the coin and the error will disappear.
> 2- restart the chain by changing the 4x "MessageStarts" at chainparams.cpp file. Then start back your node from that new compiled wallet with the new MessageStarts.
> 
> Keep in mind that you will need to set up checkpoints whenever you got the change to avoid the chain to be attacked by 51% or double spends (not now but could happen later) 
> Also checkpoints will avoid people to be split into several chains on the network.

Again, we will look into it! Rather just @sys-256 , but yes, thanks again! If you want to, you can join our discord server for faster and easier infos! [Find it here](https://discord.gg/WRr3TZ44)

**Comment by le2Ks** [comment]
> 
> 
> > > Hi @Original-Tasty, I tried your solution, but, unfortunately, it didn't work. I still get the `error code: -10 Sircoin is downloading blocks...`.
> > > Do you have any more solutions available?
> > 
> > 
> > Hi, ah ok i've thought the issue was the node won'T start at all, but if the error is about the " is downloading blocks" then that means somebody started mining and are trying to connect to your node at the second you are turning it on.
> > It's not really an error " is downloading blocks" it only means that it is waiting for a new block to be mined.
> > There are 2 options:
> > 1- turn your node back on and wait for the people to keep mining the coin and the error will disappear.
> > 2- restart the chain by changing the 4x "MessageStarts" at chainparams.cpp file. Then start back your node from that new compiled wallet with the new MessageStarts.
> > Keep in mind that you will need to set up checkpoints whenever you got the change to avoid the chain to be attacked by 51% or double spends (not now but could happen later)
> > Also checkpoints will avoid people to be split into several chains on the network.
> 
> Again, we will look into it! Rather just @sys-256 , but yes, thanks again! If you want to, you can join our discord server for faster and easier infos! [Find it here](https://discord.gg/WRr3TZ44)

Hi, okk i've joined your discord.
